name: Package workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        use-public-rspm: true
        r-version: '4.1.0'

    - name: Cache R packages
      uses: actions/cache@v2
      with:
        path: ${{ runner.tool_cache }}/R
        key: ${{ runner.os }}-r-${{ hashFiles('**/DESCRIPTION') }}
        restore-keys: |
          ${{ runner.os }}-r-

    - name: Install R package dependencies
      run: |
        Rscript -e 'remotes::install_deps(dependencies = TRUE)'

    - name: Check package
      run: |
        Rscript -e 'devtools::check()'
